include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - tmp_rovodev_**
  language:
    strict-inference: false  # Desabilitado temporariamente
    strict-raw-types: false  # Desabilitado temporariamente
  errors:
    # Transformar infos em warnings apenas para erros críticos
    avoid_print: ignore
    deprecated_member_use: warning
    unused_element: warning
    unused_local_variable: ignore
    unused_field: warning
    dead_null_aware_expression: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_unused_constructor_parameters: true
    use_build_context_synchronously: true