include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - tmp_rovodev_**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - build/**
    - .dart_tool/**
    - flutter/**
  language:
    strict-inference: false  # Desabilitado temporariamente
    strict-raw-types: false  # Desabilitado temporariamente
  errors:
    # Transformar infos em warnings apenas para erros críticos
    avoid_print: ignore
    deprecated_member_use: warning
    unused_element: ignore  # Muitos métodos privados para funcionalidades futuras
    unused_local_variable: ignore
    unused_field: ignore  # Campos podem ser usados no futuro
    dead_null_aware_expression: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_unused_constructor_parameters: true
    use_build_context_synchronously: true