include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    # unnecessary_cast: true  # Removido - não reconhecido
    # unnecessary_import: true  # Removido - não reconhecido
    avoid_unused_constructor_parameters: true