-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account (
  name text NOT NULL,
  contact_name text,
  domain text,
  phone text,
  email text,
  logo_url text,
  chave_id bigint,
  address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_chave_id_fkey FOREIGN KEY (chave_id) REFERENCES public.account_category(account_id)
);
CREATE TABLE public.account_category (
  account_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  account_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_category_pkey PRIMARY KEY (account_id)
);
CREATE TABLE public.account_client_ranking (
  account_id bigint NOT NULL,
  client_contact_id integer NOT NULL,
  last_operation_date date,
  first_operation_date date,
  notes text,
  ranking_score numeric DEFAULT 0,
  ranking_category character varying DEFAULT 'bronze'::character varying CHECK (ranking_category::text = ANY (ARRAY['bronze'::character varying::text, 'silver'::character varying::text, 'gold'::character varying::text, 'platinum'::character varying::text, 'diamond'::character varying::text])),
  total_revenue_usd numeric DEFAULT 0,
  total_revenue_brl numeric DEFAULT 0,
  total_operations integer DEFAULT 0,
  average_ticket_usd numeric DEFAULT 0,
  customer_satisfaction_score numeric DEFAULT 0,
  payment_reliability_score numeric DEFAULT 0,
  relationship_duration_days integer DEFAULT 0,
  is_premium_client boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_client_ranking_pkey PRIMARY KEY (id),
  CONSTRAINT account_client_ranking_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id)
);
CREATE TABLE public.account_communication_preferences (
  account_id bigint NOT NULL,
  contact_id bigint,
  communication_channel character varying NOT NULL CHECK (communication_channel::text = ANY (ARRAY['email'::character varying::text, 'phone'::character varying::text, 'whatsapp'::character varying::text, 'sms'::character varying::text, 'in_person'::character varying::text])),
  preferred_time_start time without time zone,
  preferred_time_end time without time zone,
  preferred_days ARRAY,
  language_preference character varying DEFAULT 'pt-BR'::character varying,
  frequency_preference character varying DEFAULT 'weekly'::character varying CHECK (frequency_preference::text = ANY (ARRAY['daily'::character varying::text, 'weekly'::character varying::text, 'monthly'::character varying::text, 'quarterly'::character varying::text])),
  auto_reminder_enabled boolean DEFAULT true,
  marketing_communications_enabled boolean DEFAULT true,
  urgent_communications_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_communication_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT account_communication_preferences_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT account_communication_preferences_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.account_employee(id)
);
CREATE TABLE public.account_document (
  account_id bigint NOT NULL,
  contact_id bigint,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['contract'::character varying::text, 'proposal'::character varying::text, 'invoice'::character varying::text, 'receipt'::character varying::text, 'certificate'::character varying::text, 'other'::character varying::text])),
  title character varying NOT NULL,
  file_name character varying,
  file_url text,
  file_size_bytes bigint,
  mime_type character varying,
  description text,
  expires_at timestamp with time zone,
  uploaded_by_user_id uuid,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_document_pkey PRIMARY KEY (id),
  CONSTRAINT account_document_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT account_document_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.account_employee(id),
  CONSTRAINT account_document_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.account_employee (
  account_id bigint NOT NULL,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  whatsapp character varying,
  extension character varying,
  notes text,
  department_id integer NOT NULL,
  position_id integer NOT NULL,
  is_primary_contact boolean DEFAULT false,
  is_decision_maker boolean DEFAULT false,
  hierarchy_level integer DEFAULT 1,
  preferred_contact_method character varying DEFAULT 'email'::character varying CHECK (preferred_contact_method::text = ANY (ARRAY['email'::character varying::text, 'phone'::character varying::text, 'whatsapp'::character varying::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_employee_pkey PRIMARY KEY (id),
  CONSTRAINT account_contact_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id)
);
CREATE TABLE public.account_interaction_log (
  account_id bigint NOT NULL,
  contact_id bigint,
  interaction_type character varying NOT NULL CHECK (interaction_type::text = ANY (ARRAY['phone_call'::character varying::text, 'email'::character varying::text, 'whatsapp'::character varying::text, 'meeting'::character varying::text, 'proposal_sent'::character varying::text, 'proposal_approved'::character varying::text, 'proposal_rejected'::character varying::text, 'invoice_sent'::character varying::text, 'payment_received'::character varying::text, 'complaint'::character varying::text, 'praise'::character varying::text, 'follow_up'::character varying::text, 'other'::character varying::text])),
  subject character varying NOT NULL,
  description text,
  outcome character varying CHECK (outcome::text = ANY (ARRAY['positive'::character varying::text, 'neutral'::character varying::text, 'negative'::character varying::text, 'pending'::character varying::text])),
  next_action text,
  next_action_date date,
  assigned_to_user_id uuid,
  interaction_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_interaction_log_pkey PRIMARY KEY (id),
  CONSTRAINT account_interaction_log_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT account_interaction_log_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.account_employee(id),
  CONSTRAINT account_interaction_log_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.account_opportunity (
  account_id bigint NOT NULL,
  contact_id bigint,
  opportunity_type character varying NOT NULL CHECK (opportunity_type::text = ANY (ARRAY['new_client'::character varying::text, 'upsell'::character varying::text, 'cross_sell'::character varying::text, 'renewal'::character varying::text, 'referral'::character varying::text])),
  title character varying NOT NULL,
  description text,
  estimated_value_usd numeric,
  estimated_value_brl numeric,
  expected_close_date date,
  assigned_to_user_id uuid,
  source character varying,
  notes text,
  probability_percentage integer DEFAULT 0 CHECK (probability_percentage >= 0 AND probability_percentage <= 100),
  stage character varying DEFAULT 'prospecting'::character varying CHECK (stage::text = ANY (ARRAY['prospecting'::character varying::text, 'qualification'::character varying::text, 'proposal'::character varying::text, 'negotiation'::character varying::text, 'closed_won'::character varying::text, 'closed_lost'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_opportunity_pkey PRIMARY KEY (id),
  CONSTRAINT account_opportunity_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT account_opportunity_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.account_employee(id),
  CONSTRAINT account_opportunity_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.account_performance_metrics (
  account_id bigint NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_revenue_usd numeric DEFAULT 0,
  total_revenue_brl numeric DEFAULT 0,
  total_operations integer DEFAULT 0,
  total_clients integer DEFAULT 0,
  average_ticket_usd numeric DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  customer_satisfaction_avg numeric DEFAULT 0,
  payment_on_time_rate numeric DEFAULT 0,
  response_time_hours numeric DEFAULT 0,
  proposal_acceptance_rate numeric DEFAULT 0,
  repeat_client_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_performance_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT account_performance_metrics_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id)
);
CREATE TABLE public.account_task (
  account_id bigint NOT NULL,
  contact_id bigint,
  assigned_to_user_id uuid,
  task_type character varying NOT NULL CHECK (task_type::text = ANY (ARRAY['follow_up'::character varying::text, 'proposal'::character varying::text, 'meeting'::character varying::text, 'call'::character varying::text, 'email'::character varying::text, 'visit'::character varying::text, 'other'::character varying::text])),
  title character varying NOT NULL,
  description text,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  completion_notes text,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying::text, 'normal'::character varying::text, 'high'::character varying::text, 'urgent'::character varying::text])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT account_task_pkey PRIMARY KEY (id),
  CONSTRAINT account_task_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT account_task_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.account_employee(id),
  CONSTRAINT account_task_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.activity_log (
  user_id text NOT NULL,
  user_name text NOT NULL,
  user_email text,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text, 'send_email'::text, 'send_whatsapp'::text, 'status_change'::text, 'follow_up'::text, 'view'::text, 'generate_pdf'::text, 'add_service'::text, 'add_product'::text, 'remove_item'::text, 'update_value'::text])),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  entity_name text,
  action_description text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  metadata jsonb,
  id bigint NOT NULL DEFAULT nextval('activity_log_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_conversation_history (
  conversation_id character varying NOT NULL,
  user_id uuid,
  message_role character varying NOT NULL CHECK (message_role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying]::text[])),
  message_content text NOT NULL,
  id bigint NOT NULL DEFAULT nextval('ai_conversation_history_id_seq'::regclass),
  tokens_used integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_conversation_history_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversation_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.ai_errors (
  user_id uuid,
  conversation_id character varying,
  request_message text,
  error_message text NOT NULL,
  error_type character varying,
  stack_trace text,
  id bigint NOT NULL DEFAULT nextval('ai_errors_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_errors_pkey PRIMARY KEY (id),
  CONSTRAINT ai_errors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.ai_interactions (
  user_id uuid,
  conversation_id character varying NOT NULL,
  request_message text NOT NULL,
  response_message text NOT NULL,
  model character varying NOT NULL,
  id bigint NOT NULL DEFAULT nextval('ai_interactions_id_seq'::regclass),
  tokens_used integer NOT NULL DEFAULT 0,
  response_time_ms integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.ai_rate_limit_tracking (
  user_id uuid,
  window_start timestamp with time zone NOT NULL,
  id bigint NOT NULL DEFAULT nextval('ai_rate_limit_tracking_id_seq'::regclass),
  request_count integer DEFAULT 0,
  last_request_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_rate_limit_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT ai_rate_limit_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.ai_usage_metrics (
  user_id uuid,
  id bigint NOT NULL DEFAULT nextval('ai_usage_metrics_id_seq'::regclass),
  date date NOT NULL DEFAULT CURRENT_DATE,
  total_requests integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  average_response_time_ms integer DEFAULT 0,
  error_count integer DEFAULT 0,
  success_count integer DEFAULT 0,
  CONSTRAINT ai_usage_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.airline (
  iata_code character varying NOT NULL UNIQUE,
  icao_code character varying,
  name character varying NOT NULL,
  callsign character varying,
  country character varying,
  country_code character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT airline_pkey PRIMARY KEY (id)
);
CREATE TABLE public.airline_favicons (
  airline_code character varying NOT NULL UNIQUE,
  airline_name character varying NOT NULL,
  favicon_url text NOT NULL,
  bucket_url text,
  id integer NOT NULL DEFAULT nextval('airline_favicons_id_seq'::regclass),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT airline_favicons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.airport (
  iata_code character varying NOT NULL UNIQUE,
  icao_code character varying,
  name character varying NOT NULL,
  city character varying NOT NULL,
  state character varying,
  country character varying NOT NULL,
  country_code character varying,
  latitude numeric,
  longitude numeric,
  timezone character varying,
  is_active boolean DEFAULT true,
  is_major_airport boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT airport_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_configuration (
  api_name character varying NOT NULL UNIQUE,
  api_display_name character varying NOT NULL,
  api_description text,
  base_url character varying NOT NULL,
  api_key_encrypted text,
  api_secret_encrypted text,
  config_data jsonb,
  auth_type character varying DEFAULT 'api_key'::character varying CHECK (auth_type::text = ANY (ARRAY['api_key'::character varying::text, 'oauth2'::character varying::text, 'bearer'::character varying::text, 'basic'::character varying::text])),
  requests_per_minute integer DEFAULT 60,
  requests_per_hour integer DEFAULT 1000,
  requests_per_day integer DEFAULT 10000,
  max_retries integer DEFAULT 3,
  retry_delay_seconds integer DEFAULT 5,
  exponential_backoff boolean DEFAULT true,
  is_active boolean DEFAULT true,
  is_test_mode boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT api_configuration_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_integration (
  operation_id bigint NOT NULL,
  integration_type character varying NOT NULL CHECK (integration_type::text = ANY (ARRAY['flightaware'::character varying::text, 'whatsapp'::character varying::text, 'google_calendar'::character varying::text, 'uber'::character varying::text, 'lyft'::character varying::text, 'other'::character varying::text])),
  api_name character varying NOT NULL,
  api_endpoint character varying,
  api_key_hash character varying,
  api_response_status integer,
  api_response_data jsonb,
  api_error_message text,
  completed_at timestamp with time zone,
  next_retry_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'success'::character varying::text, 'failed'::character varying::text, 'retry'::character varying::text])),
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  requested_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT api_integration_pkey PRIMARY KEY (id),
  CONSTRAINT api_integration_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operation(id)
);
CREATE TABLE public.api_log (
  api_configuration_id bigint NOT NULL,
  endpoint character varying NOT NULL,
  method character varying NOT NULL CHECK (method::text = ANY (ARRAY['GET'::character varying::text, 'POST'::character varying::text, 'PUT'::character varying::text, 'DELETE'::character varying::text, 'PATCH'::character varying::text])),
  request_headers jsonb,
  request_body jsonb,
  request_params jsonb,
  response_status integer,
  response_headers jsonb,
  response_body jsonb,
  response_time_ms integer,
  error_message text,
  operation_id bigint,
  user_id uuid,
  completed_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'success'::character varying::text, 'failed'::character varying::text, 'timeout'::character varying::text, 'rate_limited'::character varying::text])),
  retry_count integer DEFAULT 0,
  requested_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT api_log_pkey PRIMARY KEY (id),
  CONSTRAINT api_log_api_configuration_id_fkey FOREIGN KEY (api_configuration_id) REFERENCES public.api_configuration(id),
  CONSTRAINT api_log_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operation(id),
  CONSTRAINT api_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.audit_log (
  table_name character varying NOT NULL,
  record_id bigint NOT NULL,
  operation_type character varying NOT NULL CHECK (operation_type::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'SOFT_DELETE'::character varying]::text[])),
  user_id uuid,
  user_name character varying,
  user_email character varying,
  session_id character varying,
  ip_address inet,
  user_agent text,
  old_values jsonb,
  new_values jsonb,
  changed_fields ARRAY,
  reason text,
  notes text,
  api_endpoint character varying,
  request_id character varying,
  id bigint NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
  operation_timestamp timestamp with time zone DEFAULT now(),
  application_name character varying DEFAULT 'lecotour_dashboard'::character varying,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.backup_country_fix_20250127 (
  id integer,
  country_original character varying,
  phone character varying,
  name character varying,
  created_at timestamp with time zone
);
CREATE TABLE public.backup_country_normalization (
  id integer,
  name character varying,
  phone character varying,
  country_original character varying,
  state character varying,
  created_at timestamp with time zone,
  backup_created_at timestamp with time zone
);
CREATE TABLE public.backup_drivers_contact_removal (
  id bigint,
  name text,
  phone text,
  user_type text,
  created_at timestamp without time zone,
  removed_at timestamp without time zone DEFAULT now()
);
CREATE TABLE public.car (
  make text NOT NULL,
  model text NOT NULL,
  year integer NOT NULL,
  color text,
  license_plate text NOT NULL UNIQUE,
  photo_url text,
  capacity integer,
  price_usd numeric,
  price_updated_at timestamp with time zone,
  has_wifi boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  price_source character varying DEFAULT 'manual'::character varying,
  price_status character varying DEFAULT 'estimated'::character varying,
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT car_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact (
  contact_preview_id integer,
  is_vip boolean DEFAULT false,
  user_type USER-DEFINED DEFAULT 'normal'::user_type_enum,
  name character varying NOT NULL,
  email character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  gender character varying,
  account_id integer,
  contact_category_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  source_id integer DEFAULT 15,
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  mobile character varying,
  whatsapp character varying,
  cpf character varying,
  passport character varying,
  birth_date date,
  notes text,
  receive_emails boolean NOT NULL DEFAULT true,
  receive_whatsapp boolean NOT NULL DEFAULT true,
  created_by integer,
  updated_by integer,
  phone character varying NOT NULL,
  CONSTRAINT contact_pkey PRIMARY KEY (phone),
  CONSTRAINT contact_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT contact_contact_category_id_fkey FOREIGN KEY (contact_category_id) REFERENCES public.contact_category(id),
  CONSTRAINT contact_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id)
);
CREATE TABLE public.contact_backup_phone_pk (
  id integer,
  name character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  gender character varying,
  source_id integer,
  account_id integer,
  contact_category_id integer,
  is_vip boolean
);
CREATE TABLE public.contact_backup_structure_change_v2 (
  id integer,
  name character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  gender character varying,
  source_id integer,
  account_id integer,
  contact_category_id integer,
  is_vip boolean,
  user_type USER-DEFINED
);
CREATE TABLE public.contact_category (
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  CONSTRAINT contact_category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_preview (
  contact_preview_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  estimated_date0 date,
  estimated_date1 date,
  service_id integer,
  pax integer,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  contact_id integer,
  product_id integer,
  product_quantity integer DEFAULT 1,
  CONSTRAINT contact_preview_pkey PRIMARY KEY (contact_preview_id),
  CONSTRAINT contact_preview_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id),
  CONSTRAINT contact_preview_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contact(id),
  CONSTRAINT contact_preview_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id)
);
CREATE TABLE public.contact_preview_backup_add_product (
  contact_preview_id integer,
  created_at timestamp with time zone,
  estimated_date0 date,
  estimated_date1 date,
  service_id integer,
  pax integer,
  note text,
  contact_id integer
);
CREATE TABLE public.contact_service (
  customer_id integer NOT NULL,
  service_id integer NOT NULL,
  driver_id integer,
  car_id integer,
  agency_id integer,
  scheduled_date timestamp with time zone NOT NULL,
  number_of_passengers integer,
  pickup_location text,
  dropoff_location text,
  special_instructions text,
  final_price numeric,
  flight_number character varying,
  discount_amount numeric DEFAULT 0,
  payment_status character varying DEFAULT 'pending'::character varying,
  status character varying DEFAULT 'scheduled'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('customer_services_id_seq'::regclass),
  CONSTRAINT contact_service_pkey PRIMARY KEY (id),
  CONSTRAINT customer_services_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.account(id),
  CONSTRAINT customer_services_car_id_fkey FOREIGN KEY (car_id) REFERENCES public.car(id),
  CONSTRAINT customer_services_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver(id)
);
CREATE TABLE public.contact_updated_at_backup (
  phone character varying,
  updated_at_original timestamp with time zone,
  backup_timestamp timestamp with time zone
);
CREATE TABLE public.contact_user_type_cache (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  phone text NOT NULL UNIQUE CHECK (phone IS NOT NULL AND length(phone) >= 10),
  user_type USER-DEFINED NOT NULL CHECK (user_type <> 'normal'::user_type_enum),
  first_classified_at timestamp with time zone NOT NULL,
  classification_source text,
  notes text,
  last_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT contact_user_type_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cost_center (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  budget numeric NOT NULL DEFAULT 0.00,
  utilized numeric NOT NULL DEFAULT 0.00,
  name text NOT NULL,
  description text,
  code text NOT NULL UNIQUE,
  responsible text NOT NULL,
  department text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT cost_center_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cost_center_category (
  name text NOT NULL,
  description text,
  id integer NOT NULL DEFAULT nextval('cost_center_category_id_seq'::regclass),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cost_center_category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cost_center_expense (
  cost_center_id text NOT NULL,
  category_id integer,
  description text NOT NULL,
  amount numeric NOT NULL,
  amount_in_brl numeric NOT NULL,
  amount_in_usd numeric NOT NULL,
  expense_date date NOT NULL,
  created_by text NOT NULL,
  approved_by text,
  approved_at timestamp with time zone,
  receipt_url text,
  id integer NOT NULL DEFAULT nextval('cost_center_expense_id_seq'::regclass),
  currency_id integer NOT NULL DEFAULT 1,
  exchange_rate numeric NOT NULL DEFAULT 1.000000,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cost_center_expense_pkey PRIMARY KEY (id),
  CONSTRAINT cost_center_expense_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.cost_center(id),
  CONSTRAINT cost_center_expense_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.cost_center_category(id)
);
CREATE TABLE public.currency (
  currency_code character varying NOT NULL UNIQUE,
  currency_name character varying NOT NULL,
  exchange_rate_to_usd numeric DEFAULT 1.0000,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  currency_id integer NOT NULL DEFAULT nextval('currencies_currency_id_seq'::regclass),
  CONSTRAINT currency_pkey PRIMARY KEY (currency_id)
);
CREATE TABLE public.customer_preference (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  client_id bigint NOT NULL,
  preference_type text NOT NULL CHECK (preference_type = ANY (ARRAY['service_category'::text, 'product_category'::text, 'hotel_type'::text, 'vehicle_type'::text, 'destination'::text, 'budget_range'::text])),
  preference_value text NOT NULL,
  preference_score numeric DEFAULT 1.0,
  source text DEFAULT 'inferred'::text CHECK (source = ANY (ARRAY['explicit'::text, 'inferred'::text, 'purchase_history'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT customer_preference_pkey PRIMARY KEY (id),
  CONSTRAINT customer_preference_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.contact(id)
);
CREATE TABLE public.department (
  name character varying NOT NULL UNIQUE,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('department_id_seq'::regclass),
  CONSTRAINT department_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver (
  name text NOT NULL,
  email text UNIQUE,
  phone text,
  city_name text,
  photo_url text,
  car_status_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  is_active boolean DEFAULT true,
  whatsapp_normalizado text,
  CONSTRAINT driver_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver_car (
  driver_id integer NOT NULL,
  car_id integer NOT NULL,
  notes text,
  assigned_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('driver_cars_id_seq'::regclass),
  CONSTRAINT driver_car_pkey PRIMARY KEY (id),
  CONSTRAINT fk_driver_cars_car_id FOREIGN KEY (car_id) REFERENCES public.car(id),
  CONSTRAINT fk_driver_cars_driver_id FOREIGN KEY (driver_id) REFERENCES public.driver(id)
);
CREATE TABLE public.driver_commission (
  operation_id bigint NOT NULL UNIQUE,
  driver_id integer NOT NULL,
  base_commission_usd numeric NOT NULL,
  total_commission_usd numeric NOT NULL,
  total_commission_brl numeric,
  payment_method character varying,
  payment_date timestamp with time zone,
  payment_reference character varying,
  bonus_reason text,
  penalty_reason text,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  paid_by_user_id uuid,
  paid_at timestamp with time zone,
  bonus_usd numeric DEFAULT 0,
  penalty_usd numeric DEFAULT 0,
  exchange_rate_to_usd numeric DEFAULT 1.0000,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'paid'::character varying::text, 'cancelled'::character varying::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT driver_commission_pkey PRIMARY KEY (id),
  CONSTRAINT driver_commission_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.user(id),
  CONSTRAINT driver_commission_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver(id),
  CONSTRAINT driver_commission_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operation(id),
  CONSTRAINT driver_commission_paid_by_user_id_fkey FOREIGN KEY (paid_by_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.driver_mock (
  name text NOT NULL,
  phone text NOT NULL,
  whatsapp_normalizado text NOT NULL,
  id integer NOT NULL DEFAULT nextval('driver_mock_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT driver_mock_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver_service (
  driver_id integer NOT NULL,
  service_id integer NOT NULL,
  CONSTRAINT driver_service_pkey PRIMARY KEY (driver_id, service_id),
  CONSTRAINT driver_services_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver(id)
);
CREATE TABLE public.exchange_rate_history (
  currency_code character varying NOT NULL,
  rate_to_usd numeric NOT NULL,
  rate_date date NOT NULL,
  id bigint NOT NULL DEFAULT nextval('exchange_rate_history_id_seq'::regclass),
  source character varying DEFAULT 'banco_central_brasil'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exchange_rate_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flight_cache (
  flight_number character varying NOT NULL,
  airline_code character varying,
  departure_airport_code character varying,
  arrival_airport_code character varying,
  flight_date date NOT NULL,
  flight_data jsonb NOT NULL,
  flightaware_flight_id character varying,
  cache_key character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  is_valid boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT flight_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flight_data (
  operation_id bigint NOT NULL UNIQUE,
  flight_number character varying NOT NULL,
  airline_code character varying,
  airline_name character varying,
  departure_airport_code character varying,
  departure_airport_name character varying,
  departure_airport_city character varying,
  departure_airport_country character varying,
  arrival_airport_code character varying,
  arrival_airport_name character varying,
  arrival_airport_city character varying,
  arrival_airport_country character varying,
  scheduled_departure_time timestamp with time zone,
  scheduled_arrival_time timestamp with time zone,
  actual_departure_time timestamp with time zone,
  actual_arrival_time timestamp with time zone,
  departure_terminal character varying,
  departure_gate character varying,
  arrival_terminal character varying,
  arrival_gate character varying,
  flightaware_flight_id character varying,
  flightaware_last_updated timestamp with time zone,
  flightaware_data jsonb,
  flight_status character varying DEFAULT 'scheduled'::character varying CHECK (flight_status::text = ANY (ARRAY['scheduled'::character varying::text, 'boarding'::character varying::text, 'departed'::character varying::text, 'arrived'::character varying::text, 'delayed'::character varying::text, 'cancelled'::character varying::text, 'diverted'::character varying::text])),
  delay_minutes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT flight_data_pkey PRIMARY KEY (id),
  CONSTRAINT flight_data_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operation(id)
);
CREATE TABLE public.invoice (
  sale_id integer,
  customer_id integer,
  invoice_number character varying NOT NULL UNIQUE,
  total_amount numeric NOT NULL,
  due_date date,
  status character varying DEFAULT 'pending'::character varying,
  issued_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('invoices_id_seq'::regclass),
  created_by integer,
  updated_by integer,
  CONSTRAINT invoice_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sale(id),
  CONSTRAINT invoice_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.contact(id)
);
CREATE TABLE public.leadstintim (
  user_type USER-DEFINED DEFAULT 'normal'::user_type_enum,
  name text,
  datefirst timestamp with time zone,
  datelast timestamp with time zone,
  source text,
  status text,
  saledate timestamp with time zone,
  message character varying,
  messageid text,
  country text,
  state text,
  salevalue double precision,
  salemessage double precision,
  body character varying,
  body_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  outbound_status text CHECK (outbound_status = ANY (ARRAY['none'::text, 'pending'::text, 'queued'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text])),
  outbound_sent_at timestamp with time zone,
  outbound_error text,
  n8n_execution_id text,
  phone text CHECK (phone IS NULL OR phone <> ''::text),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  from_me text,
  whatsapp_normalizado text,
  CONSTRAINT leadstintim_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leadstintim_backup_20250106 (
  id bigint,
  created_at timestamp with time zone,
  name text,
  phone text,
  datefirst timestamp with time zone,
  datelast timestamp with time zone,
  source text,
  status text,
  saledate timestamp with time zone,
  message character varying,
  messageid text,
  country text,
  state text,
  salevalue double precision,
  salemessage double precision,
  body character varying,
  body_id integer,
  user_type USER-DEFINED,
  from_me text
);
CREATE TABLE public.leadstintim_backup_phone_fix (
  id bigint,
  created_at timestamp with time zone,
  name text,
  phone text,
  datefirst timestamp with time zone,
  datelast timestamp with time zone,
  source text,
  status text,
  saledate timestamp with time zone,
  message character varying,
  messageid text,
  country text,
  state text,
  salevalue double precision,
  salemessage double precision,
  body character varying,
  body_id integer,
  user_type USER-DEFINED
);
CREATE TABLE public.locations (
  address text NOT NULL UNIQUE,
  coordinates point,
  neighborhood text,
  city text,
  state text,
  postcode text,
  location_type text,
  establishment_name text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country text DEFAULT 'US'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  display_name text,
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.monday (
  name text,
  gender text,
  phone text,
  email text,
  city text,
  servicos text,
  observacao text,
  id bigint,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  source_id integer,
  account_id integer,
  contact_category_id integer,
  contact_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  CONSTRAINT monday_pkey PRIMARY KEY (contact_id),
  CONSTRAINT monday_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT monday_contact_category_id_fkey FOREIGN KEY (contact_category_id) REFERENCES public.contact_category(id),
  CONSTRAINT monday_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.source(id)
);
CREATE TABLE public.monday_backup (
  name text,
  sexo text,
  telefone text,
  email text,
  font text,
  cidade text,
  previsao_Start text,
  previsao_End text,
  servicos text,
  observacao text,
  contas text,
  status text,
  data_contato text,
  data_fechamento text,
  log text,
  log_atual text,
  dias_viagem text,
  dia_fechamento text,
  id_monday text,
  vendedor text,
  id bigint
);
CREATE TABLE public.monday_category_backup (
  contact_id bigint,
  name text,
  phone text,
  contact_category_id integer,
  backup_timestamp text
);
CREATE TABLE public.n8n_webhook_config (
  name text NOT NULL UNIQUE,
  webhook_url text NOT NULL,
  description text,
  id integer NOT NULL DEFAULT nextval('n8n_webhook_config_id_seq'::regclass),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT n8n_webhook_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operation (
  product_id integer,
  product_value_usd numeric,
  quantity integer,
  service_id integer,
  sale_id integer NOT NULL,
  sale_item_id integer NOT NULL,
  customer_id integer NOT NULL,
  driver_id integer,
  car_id integer,
  scheduled_date timestamp with time zone,
  estimated_duration_minutes integer,
  actual_start_time timestamp with time zone,
  actual_end_time timestamp with time zone,
  actual_duration_minutes integer,
  pickup_location text,
  dropoff_location text,
  pickup_coordinates point,
  dropoff_coordinates point,
  special_instructions text,
  customer_notes text,
  driver_notes text,
  service_value_usd numeric NOT NULL,
  whatsapp_message_sent_at timestamp with time zone,
  whatsapp_message_id character varying,
  google_calendar_event_id character varying,
  google_calendar_event_created_at timestamp with time zone,
  customer_rating integer CHECK (customer_rating >= 1 AND customer_rating <= 5),
  customer_feedback text,
  driver_rating integer CHECK (driver_rating >= 1 AND driver_rating <= 5),
  driver_feedback text,
  created_by_user_id uuid,
  assigned_by_user_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'assigned'::character varying::text, 'in_progress'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text, 'failed'::character varying::text])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying::text, 'normal'::character varying::text, 'high'::character varying::text, 'urgent'::character varying::text])),
  number_of_passengers integer DEFAULT 1,
  luggage_count integer DEFAULT 0,
  driver_commission_usd numeric DEFAULT 0,
  driver_commission_percentage numeric DEFAULT 0,
  whatsapp_message_sent boolean DEFAULT false,
  google_calendar_event_created boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  pickup_location_id uuid,
  dropoff_location_id uuid,
  CONSTRAINT operation_pkey PRIMARY KEY (id),
  CONSTRAINT operation_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.user(id),
  CONSTRAINT operation_car_id_fkey FOREIGN KEY (car_id) REFERENCES public.car(id),
  CONSTRAINT operation_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.user(id),
  CONSTRAINT operation_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver(id),
  CONSTRAINT operation_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sale(id),
  CONSTRAINT operation_sale_item_id_fkey FOREIGN KEY (sale_item_id) REFERENCES public.sale_item(sales_item_id),
  CONSTRAINT operation_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id),
  CONSTRAINT operation_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id),
  CONSTRAINT operation_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.contact(id),
  CONSTRAINT operation_pickup_location_id_fkey FOREIGN KEY (pickup_location_id) REFERENCES public.locations(id),
  CONSTRAINT operation_dropoff_location_id_fkey FOREIGN KEY (dropoff_location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.operation_history (
  operation_id bigint NOT NULL,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['created'::character varying::text, 'status_changed'::character varying::text, 'driver_assigned'::character varying::text, 'driver_unassigned'::character varying::text, 'car_assigned'::character varying::text, 'car_unassigned'::character varying::text, 'scheduled'::character varying::text, 'started'::character varying::text, 'completed'::character varying::text, 'cancelled'::character varying::text, 'note_added'::character varying::text, 'location_updated'::character varying::text])),
  old_value text,
  new_value text,
  action_data jsonb,
  performed_by_user_id uuid,
  performed_by_user_name character varying,
  performed_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT operation_history_pkey PRIMARY KEY (id),
  CONSTRAINT operation_history_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operation(id),
  CONSTRAINT operation_history_performed_by_user_id_fkey FOREIGN KEY (performed_by_user_id) REFERENCES public.user(id)
);
CREATE TABLE public.payment_method (
  method_name character varying NOT NULL UNIQUE,
  payment_method_id integer NOT NULL DEFAULT nextval('"PaymentMethods_payment_method_id_seq"'::regclass),
  CONSTRAINT payment_method_pkey PRIMARY KEY (payment_method_id)
);
CREATE TABLE public.position (
  name character varying NOT NULL UNIQUE,
  description text,
  category character varying,
  hierarchy_level integer DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('position_id_seq'::regclass),
  CONSTRAINT position_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pre_trip_action (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_id bigint NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['call'::text, 'email'::text, 'whatsapp'::text])),
  scheduled_at timestamp without time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'done'::text, 'failed'::text])),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  executed_at timestamp without time zone,
  executed_by text,
  error_message text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  priority integer DEFAULT 1,
  notes text,
  contact_phone text,
  contact_email text,
  CONSTRAINT pre_trip_action_pkey PRIMARY KEY (id),
  CONSTRAINT pre_trip_action_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id)
);
CREATE TABLE public.product (
  site_url text,
  name character varying NOT NULL,
  price_per_unit numeric NOT NULL,
  tax_percentage numeric NOT NULL,
  limited boolean NOT NULL,
  active_for_sale boolean NOT NULL,
  category_id integer,
  image_url text,
  booking_url text,
  venue_name character varying,
  venue_address text,
  event_description text,
  event_timezone character varying DEFAULT 'America/New_York'::character varying,
  available_times jsonb,
  recurring_schedule jsonb,
  product_id integer NOT NULL DEFAULT nextval('"Products_product_id_seq"'::regclass),
  CONSTRAINT product_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_category(category_id)
);
CREATE TABLE public.product_category (
  name character varying NOT NULL UNIQUE,
  description text,
  image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_id integer NOT NULL DEFAULT nextval('product_categories_category_id_seq'::regclass),
  CONSTRAINT product_category_pkey PRIMARY KEY (category_id)
);
CREATE TABLE public.provider (
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('providers_id_seq'::regclass),
  CONSTRAINT provider_pkey PRIMARY KEY (id)
);
CREATE TABLE public.provisional_invoice (
  account_id integer NOT NULL,
  invoice_number character varying NOT NULL UNIQUE,
  issue_date date NOT NULL,
  due_date date,
  total_amount numeric NOT NULL,
  net_amount numeric NOT NULL,
  currency_id integer NOT NULL,
  terms_and_conditions text,
  converted_to_sale_id integer,
  exchange_rate_to_usd numeric,
  total_amount_in_brl numeric,
  total_amount_in_usd numeric,
  sent_at timestamp with time zone,
  first_viewed_at timestamp with time zone,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  converted_at timestamp with time zone,
  expires_at timestamp with time zone,
  reminder_sent_at timestamp with time zone,
  decision_maker_name character varying,
  decision_maker_email character varying,
  decision_maker_phone character varying,
  budget_amount numeric,
  budget_currency_id integer,
  discount_amount numeric DEFAULT 0,
  status character varying DEFAULT 'Pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reminder_count integer DEFAULT 0,
  priority_level character varying DEFAULT 'normal'::character varying,
  expected_response_days integer DEFAULT 7,
  approval_chain_level integer DEFAULT 1,
  total_approval_levels integer DEFAULT 1,
  current_approval_level integer DEFAULT 1,
  requires_multiple_approvals boolean DEFAULT false,
  budget_approved boolean DEFAULT false,
  contract_terms_accepted boolean DEFAULT false,
  payment_terms_accepted boolean DEFAULT false,
  id integer NOT NULL DEFAULT nextval('provisional_invoices_id_seq'::regclass),
  CONSTRAINT provisional_invoice_pkey PRIMARY KEY (id),
  CONSTRAINT provisional_invoices_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT provisional_invoices_budget_currency_id_fkey FOREIGN KEY (budget_currency_id) REFERENCES public.currency(currency_id),
  CONSTRAINT provisional_invoices_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id)
);
CREATE TABLE public.provisional_invoice_approval (
  provisional_invoice_id bigint NOT NULL,
  approver_name character varying NOT NULL,
  approver_email character varying,
  approver_role character varying,
  approval_level integer NOT NULL,
  action character varying NOT NULL,
  comments text,
  decision_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT provisional_invoice_approval_pkey PRIMARY KEY (id),
  CONSTRAINT provisional_invoice_approvals_provisional_invoice_id_fkey FOREIGN KEY (provisional_invoice_id) REFERENCES public.provisional_invoice(id)
);
CREATE TABLE public.provisional_invoice_item (
  provisional_invoice_id integer NOT NULL,
  service_id integer NOT NULL,
  description text NOT NULL,
  unit_price numeric NOT NULL,
  item_total numeric NOT NULL,
  currency_id integer,
  exchange_rate_to_usd numeric,
  unit_price_in_brl numeric,
  unit_price_in_usd numeric,
  item_total_in_brl numeric,
  item_total_in_usd numeric,
  quantity integer NOT NULL DEFAULT 1,
  tax_percentage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('provisional_invoice_items_id_seq'::regclass),
  CONSTRAINT provisional_invoice_item_pkey PRIMARY KEY (id),
  CONSTRAINT provisional_invoice_items_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id),
  CONSTRAINT provisional_invoice_items_provisional_invoice_id_fkey FOREIGN KEY (provisional_invoice_id) REFERENCES public.provisional_invoice(id)
);
CREATE TABLE public.provisional_invoice_metric (
  provisional_invoice_id bigint NOT NULL,
  metric_type character varying NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  duration_hours numeric,
  duration_days numeric,
  stage character varying NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT provisional_invoice_metric_pkey PRIMARY KEY (id),
  CONSTRAINT provisional_invoice_metrics_provisional_invoice_id_fkey FOREIGN KEY (provisional_invoice_id) REFERENCES public.provisional_invoice(id)
);
CREATE TABLE public.provisional_invoice_reminder (
  provisional_invoice_id bigint NOT NULL,
  reminder_type character varying NOT NULL,
  sent_to_email character varying NOT NULL,
  sent_to_name character varying,
  subject text NOT NULL,
  message_content text NOT NULL,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  sent_at timestamp with time zone DEFAULT now(),
  response_received boolean DEFAULT false,
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT provisional_invoice_reminder_pkey PRIMARY KEY (id),
  CONSTRAINT provisional_invoice_reminders_provisional_invoice_id_fkey FOREIGN KEY (provisional_invoice_id) REFERENCES public.provisional_invoice(id)
);
CREATE TABLE public.quotation (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_number text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['tourism'::text, 'corporate'::text, 'event'::text, 'transfer'::text, 'other'::text])),
  client_id bigint,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text,
  agency_id bigint,
  agency_commission_rate numeric,
  travel_date timestamp without time zone NOT NULL,
  return_date timestamp without time zone,
  origin text,
  destination text,
  hotel text,
  room_type text,
  nights integer,
  vehicle text,
  driver text,
  expiration_date timestamp without time zone,
  sent_date timestamp without time zone,
  viewed_date timestamp without time zone,
  accepted_date timestamp without time zone,
  rejected_date timestamp without time zone,
  subtotal numeric NOT NULL,
  total numeric NOT NULL,
  notes text,
  special_requests text,
  cancellation_policy text,
  payment_terms text,
  created_by text NOT NULL,
  updated_at timestamp without time zone,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'viewed'::text, 'accepted'::text, 'rejected'::text, 'expired'::text, 'cancelled'::text])),
  passenger_count integer NOT NULL DEFAULT 1,
  quotation_date timestamp without time zone NOT NULL DEFAULT now(),
  discount_amount numeric NOT NULL DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_by text,
  converted_to_sale_id bigint,
  converted_at timestamp without time zone,
  last_reminder_sent_at timestamp without time zone,
  reminder_count integer DEFAULT 0,
  follow_up_date timestamp without time zone,
  assigned_to_user_id uuid,
  currency_id integer,
  exchange_rate_to_usd numeric DEFAULT 1.0,
  subtotal_in_brl numeric,
  subtotal_in_usd numeric,
  total_in_brl numeric,
  total_in_usd numeric,
  tags ARRAY,
  last_follow_up_date timestamp without time zone,
  follow_up_count integer DEFAULT 0,
  created_by_user_id text,
  created_by_user_name text,
  modified_by_user_id text,
  modified_by_user_name text,
  assigned_to_user_name text,
  commission_rate numeric DEFAULT 0.0,
  client_document text,
  CONSTRAINT quotation_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.contact(id),
  CONSTRAINT quotation_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.account(id),
  CONSTRAINT quotation_converted_to_sale_id_fkey FOREIGN KEY (converted_to_sale_id) REFERENCES public.sale(id),
  CONSTRAINT quotation_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES public.user(id),
  CONSTRAINT quotation_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id)
);
CREATE TABLE public.quotation_follow_up (
  quotation_id bigint NOT NULL,
  assigned_to text NOT NULL,
  assigned_name text NOT NULL,
  assigned_email text,
  type text NOT NULL CHECK (type = ANY (ARRAY['call'::text, 'email'::text, 'whatsapp'::text, 'meeting'::text, 'note'::text])),
  scheduled_date timestamp with time zone NOT NULL,
  completed_date timestamp with time zone,
  title text NOT NULL,
  description text,
  notes text,
  result text,
  created_by text NOT NULL,
  id bigint NOT NULL DEFAULT nextval('quotation_follow_up_id_seq'::regclass),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotation_follow_up_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_follow_up_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id)
);
CREATE TABLE public.quotation_item (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_id bigint NOT NULL,
  description text NOT NULL,
  date timestamp without time zone NOT NULL,
  value numeric NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['service'::text, 'product'::text, 'ticket'::text, 'fee'::text])),
  service_id bigint,
  product_id bigint,
  discount numeric,
  notes text,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  location text,
  provider text,
  quantity integer NOT NULL DEFAULT 1,
  currency_id integer,
  exchange_rate_to_usd numeric DEFAULT 1.0,
  value_in_brl numeric,
  value_in_usd numeric,
  total_in_brl numeric,
  total_in_usd numeric,
  CONSTRAINT quotation_item_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_item_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id),
  CONSTRAINT quotation_item_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id),
  CONSTRAINT quotation_item_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id),
  CONSTRAINT quotation_item_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id)
);
CREATE TABLE public.quotation_luggage (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_id bigint NOT NULL,
  luggage_type text NOT NULL CHECK (luggage_type = ANY (ARRAY['carry_on'::text, 'checked'::text, 'large_checked'::text, 'personal'::text])),
  quantity integer NOT NULL CHECK (quantity > 0 AND quantity <= 99),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT quotation_luggage_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_luggage_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id)
);
CREATE TABLE public.quotation_tag (
  name character varying NOT NULL UNIQUE CHECK (length(name::text) >= 2 AND length(name::text) <= 50),
  description text,
  icon character varying,
  created_by text NOT NULL,
  id bigint NOT NULL DEFAULT nextval('quotation_tag_id_seq'::regclass),
  color character varying NOT NULL DEFAULT '#3B82F6'::character varying CHECK (color::text ~* '^#[0-9A-F]{6}$'::text),
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  is_system boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotation_tag_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quotation_tag_assignment (
  quotation_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  assigned_by text NOT NULL,
  id bigint NOT NULL DEFAULT nextval('quotation_tag_assignment_id_seq'::regclass),
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotation_tag_assignment_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_tag_assignment_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id),
  CONSTRAINT quotation_tag_assignment_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.quotation_tag(id)
);
CREATE TABLE public.quotation_template (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  description text,
  type text NOT NULL CHECK (type = ANY (ARRAY['tourism'::text, 'corporate'::text, 'event'::text, 'transfer'::text, 'other'::text])),
  default_notes text,
  default_cancellation_policy text,
  default_payment_terms text,
  created_by text NOT NULL,
  default_items jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT quotation_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.quotation_timeline (
  quotation_id bigint NOT NULL,
  event_type text NOT NULL,
  title text NOT NULL,
  description text,
  created_by text,
  metadata jsonb,
  id bigint NOT NULL DEFAULT nextval('quotation_timeline_id_seq'::regclass),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT quotation_timeline_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_timeline_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id)
);
CREATE TABLE public.quotation_version (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_id bigint NOT NULL,
  version_number integer NOT NULL,
  snapshot jsonb NOT NULL,
  changed_by text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT quotation_version_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_version_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotation(id)
);
CREATE TABLE public.role (
  name text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  CONSTRAINT role_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rotas_operacionais (
  voo character varying NOT NULL,
  cia character varying NOT NULL,
  nome_cia character varying NOT NULL,
  origem character varying NOT NULL,
  destino character varying NOT NULL,
  terminal_origem character varying,
  terminal_destino character varying,
  horario_std time without time zone NOT NULL,
  horario_sta time without time zone NOT NULL,
  check_in_area character varying,
  desembarque_area character varying,
  observacoes text,
  id integer NOT NULL DEFAULT nextval('rotas_operacionais_id_seq'::regclass),
  tempo_antecedencia_min integer DEFAULT 180,
  tempo_espera_min integer DEFAULT 60,
  dias_semana character varying DEFAULT '1234567'::character varying,
  ativo boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT rotas_operacionais_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sale (
  total_amount numeric NOT NULL,
  payment_method character varying,
  notes text,
  price_original numeric,
  price_in_brl numeric,
  price_in_usd numeric,
  total_amount_brl numeric,
  total_amount_usd numeric,
  due_date timestamp without time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'pending'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  sale_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  exchange_rate_to_usd numeric DEFAULT NULL::numeric,
  id integer NOT NULL DEFAULT nextval('sales_id_seq'::regclass),
  tags ARRAY,
  sale_number character varying UNIQUE,
  internal_notes text,
  discount_amount_usd numeric DEFAULT 0,
  tax_amount_usd numeric DEFAULT 0,
  net_amount_usd numeric,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  customer_id integer NOT NULL,
  user_id uuid NOT NULL,
  currency_id integer NOT NULL,
  created_by integer,
  updated_by integer,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'partial'::character varying, 'paid'::character varying, 'overdue'::character varying, 'refunded'::character varying]::text[])),
  CONSTRAINT sale_pkey PRIMARY KEY (id),
  CONSTRAINT sales_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id),
  CONSTRAINT sale_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.user(id),
  CONSTRAINT sale_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.user(id),
  CONSTRAINT sale_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id),
  CONSTRAINT sale_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.contact(id)
);
CREATE TABLE public.sale_cancellation_item (
  cancellation_log_id integer NOT NULL,
  service_id integer NOT NULL,
  service_name character varying NOT NULL,
  service_description text,
  quantity integer NOT NULL,
  unit_price_at_sale numeric NOT NULL,
  subtotal numeric NOT NULL,
  item_total numeric NOT NULL,
  currency_id integer NOT NULL,
  currency_code character varying NOT NULL,
  exchange_rate_to_usd numeric NOT NULL,
  unit_price_in_brl numeric NOT NULL,
  unit_price_in_usd numeric NOT NULL,
  item_total_in_brl numeric NOT NULL,
  item_total_in_usd numeric NOT NULL,
  pax integer DEFAULT 1,
  discount_percentage numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  surcharge_percentage numeric DEFAULT 0.00,
  surcharge_amount numeric DEFAULT 0.00,
  tax_percentage numeric DEFAULT 0.00,
  tax_amount numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('sales_cancellation_items_id_seq'::regclass),
  CONSTRAINT sale_cancellation_item_pkey PRIMARY KEY (id),
  CONSTRAINT sales_cancellation_items_cancellation_log_id_fkey FOREIGN KEY (cancellation_log_id) REFERENCES public.sale_cancellation_log(id)
);
CREATE TABLE public.sale_cancellation_log (
  sale_id integer NOT NULL,
  customer_id integer NOT NULL,
  customer_name character varying NOT NULL,
  customer_email character varying,
  customer_phone character varying,
  user_id character varying NOT NULL,
  user_name character varying NOT NULL,
  total_amount numeric NOT NULL,
  total_amount_brl numeric NOT NULL,
  total_amount_usd numeric NOT NULL,
  currency_id integer NOT NULL,
  currency_code character varying NOT NULL,
  exchange_rate_to_usd numeric NOT NULL,
  original_status character varying NOT NULL,
  cancellation_reason text NOT NULL,
  cancellation_type character varying NOT NULL,
  refund_date timestamp with time zone,
  refund_method character varying,
  refund_transaction_id character varying,
  cancelled_by_user_id character varying NOT NULL,
  cancelled_by_user_name character varying NOT NULL,
  notes text,
  tags ARRAY,
  total_paid numeric DEFAULT 0.00,
  total_paid_brl numeric DEFAULT 0.00,
  total_paid_usd numeric DEFAULT 0.00,
  remaining_amount numeric DEFAULT 0.00,
  remaining_amount_brl numeric DEFAULT 0.00,
  remaining_amount_usd numeric DEFAULT 0.00,
  refund_required boolean DEFAULT false,
  refund_amount numeric DEFAULT 0.00,
  refund_amount_brl numeric DEFAULT 0.00,
  refund_amount_usd numeric DEFAULT 0.00,
  refund_status character varying DEFAULT 'pending'::character varying,
  cancelled_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('sales_cancellation_logs_id_seq'::regclass),
  CONSTRAINT sale_cancellation_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sale_cancellation_payment (
  cancellation_log_id integer NOT NULL,
  payment_method_id integer,
  payment_method_name character varying,
  amount numeric NOT NULL,
  currency_id integer NOT NULL,
  currency_code character varying NOT NULL,
  exchange_rate_to_usd numeric NOT NULL,
  amount_in_brl numeric NOT NULL,
  amount_in_usd numeric NOT NULL,
  payment_date timestamp with time zone NOT NULL,
  transaction_id character varying,
  refund_date timestamp with time zone,
  refund_transaction_id character varying,
  is_advance_payment boolean DEFAULT false,
  refund_required boolean DEFAULT false,
  refund_status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('sales_cancellation_payments_id_seq'::regclass),
  CONSTRAINT sale_cancellation_payment_pkey PRIMARY KEY (id),
  CONSTRAINT sales_cancellation_payments_cancellation_log_id_fkey FOREIGN KEY (cancellation_log_id) REFERENCES public.sale_cancellation_log(id)
);
CREATE TABLE public.sale_item (
  sales_id integer NOT NULL,
  unit_price_at_sale numeric NOT NULL,
  item_total numeric NOT NULL,
  currency_id integer,
  exchange_rate_to_usd numeric,
  unit_price_in_brl numeric,
  unit_price_in_usd numeric,
  item_total_in_brl numeric,
  item_total_in_usd numeric,
  product_id integer,
  quantity integer NOT NULL DEFAULT 1,
  tax_percentage_at_sale numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pax integer DEFAULT 1,
  discount_percentage numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  surcharge_percentage numeric DEFAULT 0.00,
  surcharge_amount numeric DEFAULT 0.00,
  tax_amount numeric DEFAULT 0.00,
  subtotal numeric DEFAULT 0.00,
  tax_percentage numeric DEFAULT 0.00,
  service_id integer NOT NULL,
  sales_item_id integer NOT NULL DEFAULT nextval('sales_items_sales_item_id_seq'::regclass),
  description text,
  requires_flight_data boolean DEFAULT false,
  requires_driver boolean DEFAULT true,
  requires_vehicle boolean DEFAULT true,
  driver_commission_percentage numeric DEFAULT 0,
  driver_commission_fixed_usd numeric DEFAULT 0,
  updated_by integer,
  created_by integer,
  CONSTRAINT sale_item_pkey PRIMARY KEY (sales_item_id),
  CONSTRAINT sales_items_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id),
  CONSTRAINT sales_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(product_id),
  CONSTRAINT sale_item_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES public.sale(id),
  CONSTRAINT sale_item_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id)
);
CREATE TABLE public.sale_payment (
  sales_id integer NOT NULL,
  amount numeric NOT NULL,
  currency_id integer NOT NULL,
  payment_date timestamp with time zone NOT NULL,
  transaction_id character varying,
  exchange_rate_to_usd numeric,
  amount_in_brl numeric,
  amount_in_usd numeric,
  payment_method_id integer NOT NULL DEFAULT 1,
  is_advance_payment boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_id integer NOT NULL DEFAULT nextval('sales_payments_payment_id_seq'::regclass),
  currency_code character varying DEFAULT 'USD'::character varying,
  exchange_rate_date date DEFAULT CURRENT_DATE,
  exchange_rate_source character varying DEFAULT 'banco_central_brasil'::character varying,
  is_refunded boolean DEFAULT false,
  refund_date timestamp with time zone,
  refund_transaction_id character varying,
  notes text,
  processed_by_user_id uuid,
  created_by integer,
  updated_by integer,
  CONSTRAINT sale_payment_pkey PRIMARY KEY (payment_id),
  CONSTRAINT sales_payments_currency_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id),
  CONSTRAINT sale_payment_processed_by_user_id_fkey FOREIGN KEY (processed_by_user_id) REFERENCES public.user(id),
  CONSTRAINT sale_payment_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_method(payment_method_id),
  CONSTRAINT sale_payment_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES public.sale(id)
);
CREATE TABLE public.service (
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  servicetype_id integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('services_id_seq'::regclass),
  created_by integer,
  updated_by integer,
  CONSTRAINT service_pkey PRIMARY KEY (id),
  CONSTRAINT services_servicetype_id_fkey FOREIGN KEY (servicetype_id) REFERENCES public.service_category(id)
);
CREATE TABLE public.service_category (
  name character varying NOT NULL UNIQUE,
  description text,
  icon character varying,
  color character varying DEFAULT '#3B82F6'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id integer NOT NULL DEFAULT nextval('services_types_id_seq'::regclass),
  CONSTRAINT service_category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_configuration (
  service_id integer NOT NULL UNIQUE,
  requires_flight_data boolean DEFAULT false,
  requires_driver_assignment boolean DEFAULT true,
  requires_car_assignment boolean DEFAULT true,
  requires_pickup_location boolean DEFAULT true,
  requires_dropoff_location boolean DEFAULT true,
  default_driver_commission_percentage numeric DEFAULT 0,
  default_driver_commission_fixed_usd numeric DEFAULT 0,
  auto_create_google_calendar_event boolean DEFAULT false,
  auto_send_whatsapp_message boolean DEFAULT false,
  auto_fetch_flight_data boolean DEFAULT false,
  notify_driver_minutes_before integer DEFAULT 30,
  notify_customer_minutes_before integer DEFAULT 60,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT service_configuration_pkey PRIMARY KEY (id),
  CONSTRAINT service_configuration_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id)
);
CREATE TABLE public.service_payment (
  customer_name text,
  subtasks text,
  service_date date,
  service_name text,
  charged_amount numeric,
  commission_amount numeric,
  payment_method text,
  amount_to_receive numeric,
  is_paid boolean,
  creation_log text,
  driver_name text,
  lead_source text,
  margin numeric,
  salesperson text,
  payment_date date,
  commission_margin numeric,
  item_id bigint
);
CREATE TABLE public.service_price_history (
  service_id integer NOT NULL,
  price numeric NOT NULL,
  currency_id integer NOT NULL,
  effective_date date NOT NULL,
  price_history_id integer NOT NULL DEFAULT nextval('"ServicePriceHistory_price_history_id_seq"'::regclass),
  CONSTRAINT service_price_history_pkey PRIMARY KEY (price_history_id)
);
CREATE TABLE public.service_route (
  services_routes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT service_route_pkey PRIMARY KEY (id)
);
CREATE TABLE public.source (
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true,
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  CONSTRAINT source_pkey PRIMARY KEY (id)
);
CREATE TABLE public.status (
  status character varying NOT NULL,
  status_id integer NOT NULL DEFAULT nextval('"Status_status_id_seq"'::regclass),
  CONSTRAINT status_pkey PRIMARY KEY (status_id)
);
CREATE TABLE public.user (
  permissions ARRAY DEFAULT '{}'::text[],
  username character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying,
  avatar character varying,
  department_id integer,
  last_login_at timestamp with time zone,
  role character varying DEFAULT 'user'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id uuid NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id),
  CONSTRAINT user_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.department(id),
  CONSTRAINT user_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.wa_messages (
  thread_id uuid NOT NULL,
  direction text NOT NULL,
  from_instance text NOT NULL,
  to_instance text NOT NULL,
  from_number text NOT NULL,
  to_number text NOT NULL,
  raw_payload jsonb NOT NULL,
  body_text text,
  id bigint NOT NULL DEFAULT nextval('wa_messages_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wa_messages_pkey PRIMARY KEY (id),
  CONSTRAINT wa_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.wa_threads(id)
);
CREATE TABLE public.wa_threads (
  id_cliente integer NOT NULL,
  id_driver integer NOT NULL,
  instancia_cliente text NOT NULL,
  instancia_agente text NOT NULL,
  apelido_cliente text NOT NULL,
  codigo_cliente text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'ativo'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wa_threads_pkey PRIMARY KEY (id),
  CONSTRAINT wa_threads_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES public.leadstintim(id),
  CONSTRAINT wa_threads_id_driver_fkey FOREIGN KEY (id_driver) REFERENCES public.driver(id)
);
CREATE TABLE public.whatsapp_message_templates (
  name text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category = ANY (ARRAY['boas_vindas'::text, 'lembrete'::text, 'confirmacao'::text, 'follow_up'::text, 'operacional'::text, 'marketing'::text])),
  body text NOT NULL,
  variables ARRAY,
  id bigint NOT NULL DEFAULT nextval('whatsapp_message_templates_id_seq'::regclass),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  usage_count integer DEFAULT 0,
  CONSTRAINT whatsapp_message_templates_pkey PRIMARY KEY (id)
);